name = "Cochain"
version = "0.1.0"
defaultTargets = ["cochain"]

[[lean_lib]]
name = "Cochain"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.24.0"

[[require]]
name = "LieRinehart"
git = "https://github.com/Chen2357/LieRinehart"